spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/login_system
    username: postgres
    password: root
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
  application:
    name: Client Managment System
    author: Jahangirzada Nurlan
    version: 1.0.0
